name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  my-job:
      runs-on: ubuntu-latest

      steps:
        - name: Free space
          run: |
            echo "Free space:"
            df -h

        - name: Check out code
          uses: actions/checkout@v3

        - name: Setup Cog
          uses: replicate/setup-cog@v1.0.3
          with:
            token: ${{ secrets.REPLICATE_API_TOKEN }}

        - name: Push to Replicate
          run: |
            cog push r8.im/benlin924/test5

        - name: Free space
          run: |
            echo "Free space:"
            df -h
